import React from "react";
import Head from "next/head";
import Link from "next/link";
import styles from "@/styles/Home.module.css";
import { Navbar, Text, Dropdown, Avatar } from "@nextui-org/react";
import { useRouter } from "next/router";
import Image from "next/image";
import Dinsos from "../../../public/dinsos.png";
export default function Layout({ children, title }) {
  const route = useRouter();

  const Navigation = [
    {
      title: "Beranda",
      href: "/",
      icon: (props) => (
        <svg
          {...props}
          viewBox="0 0 24 24"
          fill="currentColor"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            opacity="0.4"
            d="M3 9.84719C3 8.99027 3.36644 8.17426 4.00691 7.60496L9.34255 2.86217C10.8581 1.51502 13.1419 1.51502 14.6575 2.86217L19.9931 7.60496C20.6336 8.17426 21 8.99027 21 9.84719V18C21 20.2091 19.2091 22 17 22H7C4.79086 22 3 20.2091 3 18V9.84719Z"
          />
          <path
            d="M10 18H14"
            stroke="#28303F"
            stroke-width="1.5"
            stroke-linecap="round"
          />
        </svg>
      ),
    },
    {
      title: "Profil Dinas",
      href: "/profil-dinas",
      icon: (props) => (
        <svg
          {...props}
          viewBox="0 0 24 24"
          fill="currentColor"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            opacity="0.4"
            d="M3 9.84719C3 8.99027 3.36644 8.17426 4.00691 7.60496L9.34255 2.86217C10.8581 1.51502 13.1419 1.51502 14.6575 2.86217L19.9931 7.60496C20.6336 8.17426 21 8.99027 21 9.84719V18C21 20.2091 19.2091 22 17 22H7C4.79086 22 3 20.2091 3 18V9.84719Z"
          />
          <path
            d="M10 18H14"
            stroke="#28303F"
            stroke-width="1.5"
            stroke-linecap="round"
          />
        </svg>
      ),
    },
    {
      title: "Visi & Misi",
      href: "/visi-misi",
      icon: (props) => (
        <svg
          {...props}
          viewBox="0 0 24 24"
          fill="currentColor"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            opacity="0.4"
            d="M3 9.84719C3 8.99027 3.36644 8.17426 4.00691 7.60496L9.34255 2.86217C10.8581 1.51502 13.1419 1.51502 14.6575 2.86217L19.9931 7.60496C20.6336 8.17426 21 8.99027 21 9.84719V18C21 20.2091 19.2091 22 17 22H7C4.79086 22 3 20.2091 3 18V9.84719Z"
          />
          <path
            d="M10 18H14"
            stroke="#28303F"
            stroke-width="1.5"
            stroke-linecap="round"
          />
        </svg>
      ),
    },
    {
      title: "Layanan Pengaduan",
      href: "/layanan-pengaduan",
      icon: (props) => (
        <svg
          {...props}
          viewBox="0 0 24 24"
          fill="currentColor"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            opacity="0.4"
            d="M3 9.84719C3 8.99027 3.36644 8.17426 4.00691 7.60496L9.34255 2.86217C10.8581 1.51502 13.1419 1.51502 14.6575 2.86217L19.9931 7.60496C20.6336 8.17426 21 8.99027 21 9.84719V18C21 20.2091 19.2091 22 17 22H7C4.79086 22 3 20.2091 3 18V9.84719Z"
          />
          <path
            d="M10 18H14"
            stroke="#28303F"
            stroke-width="1.5"
            stroke-linecap="round"
          />
        </svg>
      ),
    },
  ];
  const menuItems = [
    { key: "new", name: "New File" },
    { key: "copy", name: "Copy Link" },
    { key: "edit", name: "Edit File" },
    { key: "delete", name: "Delete File" },
  ];

  return (
    <>
      <Head>
        <title>{title ?? ""} Dinas Sosial Prov. Sumatera Barat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <Navbar
        className="shadow-2xl fixed"
        disableBlur
        variant="sticky"
        shouldHideOnScroll
        maxWidth={"fluid"}
      >
        <Navbar.Toggle showIn="xs" />
        <Navbar.Brand
          css={{
            "@xs": {
              w: "12%",
            },
          }}
        >
          <Navbar.Content>
            <div className="w-[400px]">
              <Image src={Dinsos} alt="#" />
            </div>
          </Navbar.Content>
          {/* <Text b color="inherit" hideIn="xs">
            ACME
        </Text> */}
        </Navbar.Brand>

        <Navbar.Content
          css={{
            "@xs": {
              jc: "flex-end",
            },
          }}
        >
          <div className="hidden lg:flex lg:gap-4 place-items-center text-sm">
            {Navigation.map((e, i) => {
              return (
                <Link
                  className={
                    route.pathname === e.href
                      ? "text-slate-900 font-bold"
                      : "hover:text-slate-900"
                  }
                  key={i}
                  href={e.href}
                >
                  <div className="flex gap-1 items-center">
                    <e.icon className="h-6 w-6" />
                    {e.title}{" "}
                  </div>
                </Link>
              );
            })}
            <Dropdown>
              <Dropdown.Button
                className="p-0 font-normal text-sm"
                color={""}
                flat
              >
                Publikasi
              </Dropdown.Button>
              <Dropdown.Menu aria-label="Dynamic Actions" items={menuItems}>
                {(item) => (
                  <Dropdown.Item
                    key={item.key}
                    color={item.key === "delete" ? "error" : "default"}
                  >
                    {item.name}
                  </Dropdown.Item>
                )}
              </Dropdown.Menu>
            </Dropdown>
          </div>
          <Dropdown placement="bottom-right">
            <Navbar.Item>
              <Dropdown.Trigger>
                <Avatar
                  bordered
                  as="button"
                  color="warning"
                  size="md"
                  src="https://i.pravatar.cc/150?u=a042581f4e29026704d"
                />
              </Dropdown.Trigger>
            </Navbar.Item>
            <Dropdown.Menu
              aria-label="User menu actions"
              color="warning"
              onAction={(actionKey) => route.push(`/${actionKey}`)}
            >
              <Dropdown.Item key="profile" css={{ height: "$18" }}>
                <Text b color="inherit" css={{ d: "flex" }}>
                  Ini Nama
                </Text>
                <Text b color="inherit" css={{ d: "flex" }}>
                  Ini Email
                </Text>
              </Dropdown.Item>
              <Dropdown.Item key="admin" withDivider>
                Dashboard Admin
              </Dropdown.Item>
              <Dropdown.Item key="edit-profile">Edit Profile</Dropdown.Item>

              <Dropdown.Item key="login" withDivider color="error">
                Login
              </Dropdown.Item>
            </Dropdown.Menu>
          </Dropdown>
        </Navbar.Content>
        <Navbar.Collapse disableAnimation>
          {Navigation.map((e, i) => (
            <Navbar.CollapseItem
              key={i}
              activeColor="warning"
              css={{
                color: i === Navigation.length - 1 ? "$error" : "",
              }}
              isActive={i === 2}
            >
              <Link
                color="inherit"
                css={{
                  minWidth: "100%",
                }}
                href={e.href}
              >
                {e.title}
              </Link>
            </Navbar.CollapseItem>
          ))}
        </Navbar.Collapse>
      </Navbar>
      <main>{children}</main>
      <footer className="text-center text-white">
        <div className="bg-sky-900 flex justify-between items-center p-10">
          <div className="flex flex-col items-start">
            <h1>Jl Khatib Sulaiman No. 5 Kota Padang</h1>
            <h1>© 2023 - Selviani</h1>
          </div>
          <iframe
            className="rounded-lg"
            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3989.298709884516!2d100.35850581405303!3d-0.9247082355977271!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2fd4b8d75e136e61%3A0xedc7d0fa6b6017af!2sDinas%20Sosial%20Pemprov%20Sumatera%20Barat!5e0!3m2!1sid!2sid!4v1678888971799!5m2!1sid!2sid"
            width="600"
            height="200"
          ></iframe>
        </div>
      </footer>
    </>
  );
}
