import React from "react";
import Head from "next/head";
import NavbarC from "./navbarC";
import FooterC from "./footerC";

export default function Layout({ children, title }) {
  return (
    <>
      <Head>
        <title>{title ?? ""} Dinas Sosial Prov. Sumatera Barat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <NavbarC />
      <main>{children}</main>
      <FooterC />
    </>
  );
}
